spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 5000
      password: 123456
      lettuce:
        pool:
          max-idle: 8  #最大空闲连接数
          min-idle: 4  #最小空闲连接数
          max-active: 64  #最大活跃连接数
          max-wait: 3000ms  #没有连接可用时最大的等待时长
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /thumbSystem
    username: RabbitMQ
    password: RabbitMQ
    template:
      retry:
        enabled: true
        max-interval: 10000ms # 连接时的最大等待时长
        initial-interval: 1000ms # 最大重试次数
        multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false

knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080
  tomcat:
    threads:
      max: 300
      min-spare: 20
    accept-count: 200
logging:
  level:
    com.wen: INFO
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 整合 Prometheus + Grafana
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}  # 会自动读取你的 thumb-backend
  endpoint:
    health:
      show-details: always

application.title: "文的点赞系统"
#查询博客的uri 用于放行请求 使没登陆的用户也能查看(如果直接配置在配置类里过滤就会让登录的用户也获取不到userId 所以这里在拦截器里配置)
blog:
  one: "/api/blog"
  list: "/api/blog/list"